name: Prepare and Push Release Branch

on:
  push:
    tags:
      - '*'

jobs:
  prepare-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures the entire history and tags are fetched

    - name: Configure Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Setup Environment
      run: |
        mkdir -p publish
        if [ -d out ]; then mv out/* publish/; fi
        find src -name "*.d.ts" -exec mv {} publish/ \;

    - name: Create Release Branch
      run: |
        git checkout --orphan release
        git rm -rf .
        mv publish/* .
        rmdir publish
        git add .
        git commit -m "Prepare release branch with selected contents"
        git push origin release
